### ISSUE TITLE
npm install Erro

### ISSUE THREAD

**Issue by at77ms** [telerik/kendo-angular-quickstart-cli#4]
D:\ng\kendo>cnpm install
x Install fail! Error: [@progress/kendo-angular-buttons@^1.0.0] GET https://regi
stry.npm.taobao.org/@progress%2Fkendo-angular-buttons/%3E%3D1.0.0%20%3C2.0.0 res
ponse 404 status
Error: [@progress/kendo-angular-buttons@^1.0.0] GET https://registry.npm.taobao.
org/@progress%2Fkendo-angular-buttons/%3E%3D1.0.0%20%3C2.0.0 response 404 status

    at get (d:\node\node_modules\cnpm\node_modules\npminstall\lib\get.js:51:17)
    at get.next (<anonymous>)
    at onFulfilled (d:\node\node_modules\cnpm\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
npminstall version: 2.30.0
npminstall args: d:\node\node.exe d:\node\node_modules\cnpm\node_modules\npminst
all\bin\install.js --china --userconfig=d:\Users\asnphlr\.cnpmrc --disturl=https
://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

win 7 x64
node v7.10.0
npm 4.2.0

is there something wrong in the package.json file ???

**Comment by at77ms** [comment]
i search in npmjs.com, there no such 'kendo-angular-buttons' module in the npm

**Comment by tsvetomir** [comment]
The packages are not available on the public NPM registry. You need to setup your access to the [Progress NPM Registry](http://www.telerik.com/kendo-angular-ui/components/installation/npm-registry/)
